#pragma once

#include "NativeGameplayTags.h"

/** Нативные теги, на которые опирается C++. Остальные — в Config/DefaultGameplayTags.ini. */
namespace PrimTags
{
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intent);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intent_Door_Open);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intent_Door_Close);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intent_Object_Inspect);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intent_NPC_Talk);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intent_NPC_Follow);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intent_Vehicle_Enter);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Intent_Metro_PassGate);

PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Economy_Salary);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Economy_Purchase);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Economy_Fare_Metro);
PRIMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Economy_Fine);
} // namespace PrimTags
