[/Script/EngineSettings.GameMapsSettings]
GlobalDefaultGameMode=/Script/PrimorskySim.PrimGameMode
GlobalDefaultServerGameMode=/Script/PrimorskySim.PrimGameMode

[/Script/Engine.RendererSettings]
r.Nanite.ProjectEnabled=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.VirtualTextures=True

[SystemSettings]
; Серверный стриминг World Partition (Docs/World.md §6)
wp.Runtime.EnableServerStreaming=1

[/Script/OnlineSubsystemUtils.IpNetDriver]
NetServerMaxTickRate=30
